### ISSUE TITLE
[FEA] Edge Operators Refactor

### ISSUE THREAD

**Issue by ryanolson** [nv-morpheus/MRC#152]
We should revisit the Edge Operators requirement of inheriting from `std::enable_shared_from_this`.

When these work was initially done, the segment builder was not able to capture ownership of non-Runnables which meant that the ownership of the edge operators was unable to be captured by the builder. Using `enable_shared_from_this` allowed the edge, i.e. the `shared_ptr<channel::IngressHandle>` to capture ownership of the operator and because the formation of the edge was the transfer of this ingress handle to a source, the operators were maintained as part of the edge connections.

We should either protect the public constructions and enforce the creation of an edge operator via a static `create` method, or relax the inheritance and ensure the segment builder take proper ownership.

In it's current state, user can construct an edge operator on the stack or via a unique_ptr and see runtime failures. A static `create` method would ensure the object is constructed as a shared_ptr if we maintain the current inheritance.

**Comment by mdemoret-nv** [comment]
Edges and Operator nodes no longer inherit from `std::enable_shared_from_this`. Closing
