### ISSUE TITLE
Remove vcpkg

### ISSUE THREAD

**Issue by ryanolson** [nv-morpheus/MRC#2]
The repo still references vcpkg which has been superceded by conda.

Resolution of the issue removes all vcpkg references as that build path will not be maintained.

**Comment by mdemoret-nv** [comment]
> Is this something we want to do for Morpheus as well? @mdemoret-nv

Yes. the `vcpkg.json` file has already been removed from Morpheus but the CMake commands still remain.

**Comment by mdemoret-nv** [comment]
Vcpkg commands have been removed with the addition of the utilities repo.
