### ISSUE TITLE
Update formatter and linter options

### ISSUE THREAD

**Issue by ryanolson** [nv-morpheus/MRC#219]
When moving from clang-format-12 to clang-format-15, there are two places in the code annotated with `todo(clang-format-15)`  where a block of code has its formatting disabled.

We should upgrade `clang-tidy` and `clang-format` to the latest versions and evaluate if we need to make any adjustments to the settings.

Note: originally the todos were annotated with `clang-format-14`, but updated that to reflect `clang-format-15` and also to trigger a rerun of the CI.

**Comment by ryanolson** [comment]
See commit: 941f33a

**Comment by mdemoret-nv** [comment]
Additionally, we should use this as an opportunity to update some annoying clang-tidy/clang-format options. Open to suggestions. Working list:

- Figure out a way to have two different naming conventions for member using statements (inside of a class. i.e `MyClass::my_class_t`) vs global typedefs (i.e. `using InstanceID = std::uint_32_t`)
- See if its possible to enforce keeping the .hpp and .cpp order synced.
