### ISSUE TITLE
[BUG]: pytest test_edges.py generates a lot of stderr from services.cpp

### ISSUE THREAD

**Issue by pdmack** [nv-morpheus/MRC#324]
### Version

23.07

### Which installation method(s) does this occur on?

Conda, Source

### Describe the bug.

There are numerous XFAIL in test_edges.py. I'm not sure if there's a complete 1:1 correspondence but they each seem to trigger:

`service.cpp:136] mrc::internal::service: service was not joined before being destructed; issuing join`

### Minimum reproducible example

```shell
pytest -vvvvv python/tests/test_edges.py
```

### Relevant log output

https://gist.github.com/pdmack/2449e2c1069ac345cc837b0962dde5bf#file-gistfile1-txt

### Code of Conduct

- [X] I agree to follow MRC's Code of Conduct
- [X] I have searched the [open bugs](https://github.com/nv-morpheus/MRC/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and have found no duplicates for this bug report

**Comment by dagardner-nv** [comment]
I'm unable to reproduce this in `branch-24.03`, although I can in 23.07, someone else must have already fixed this on their own.
